export const ADD_TO_LIST_REQUEST = "ADD_TO_LIST_REQUEST";
export const ADD_TO_LIST_SUCCESS = "ADD_TO_LIST_SUCCESS";
export const DELETE_FROM_LIST = "DELETE_FROM_LIST";
export const DELETE_ALL_LIST = "DELETE_ALL_LIST";
